# Generated by Django 4.0.2 on 2022-02-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('value', models.FloatField()),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Competitor',
                'verbose_name_plural': 'Competitors',
            },
        ),
        migrations.CreateModel(
            name='DayPassResort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resort', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Day Pass Resort',
                'verbose_name_plural': 'Day Pass Resort',
            },
        ),
    ]
