# Generated by Django 4.0.2 on 2022-02-05 21:57

from django.db import migrations, models
import django.db.models.deletion
import gfklookupwidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('giveaway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveAway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('number_of_winners', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'GiveAway',
                'verbose_name_plural': 'GiveAway',
            },
        ),
        migrations.CreateModel(
            name='GiveAwayWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', gfklookupwidget.fields.GfkLookupField()),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveaway.competitor')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveaway.giveaway')),
            ],
            options={
                'verbose_name': 'GiveAway',
                'verbose_name_plural': 'GiveAway',
            },
        ),
    ]
