# Generated by Django 4.0.2 on 2022-02-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0002_giveaway_giveawaywinner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giveawaywinner',
            options={'verbose_name': 'GiveAway Winner', 'verbose_name_plural': 'GiveAway Winner'},
        ),
    ]
