# Generated by Django 4.0.2 on 2022-02-05 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('giveaway', '0003_alter_giveawaywinner_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveawaywinner',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'giveaway'), ('model', 'article')), models.Q(('app_label', 'giveaway'), ('model', 'daypassresort')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
